#!/usr/bin/env bash
# render-dockerfiles.sh
# Generate variants/<major>/Dockerfile for every Postgres major in manifest.json
# by substituting the __TOKENS__ in Dockerfile.template.
#
# Usage: scripts/render-dockerfiles.sh
# Requires: jq
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="${REPO_ROOT}/Dockerfile.template"
MANIFEST="${REPO_ROOT}/manifest.json"

command -v jq >/dev/null || { echo "error: jq is required" >&2; exit 1; }
[ -f "$TEMPLATE" ] || { echo "error: missing $TEMPLATE" >&2; exit 1; }
[ -f "$MANIFEST" ] || { echo "error: missing $MANIFEST" >&2; exit 1; }

PGVECTOR="$(jq -r '.pgvector' "$MANIFEST")"
MAJORS="$(jq -r '.pg_majors[]' "$MANIFEST")"

for major in $MAJORS; do
  digest="$(jq -r --arg m "$major" '.alpine_digests[$m]' "$MANIFEST")"
  if [ -z "$digest" ] || [ "$digest" = "null" ]; then
    echo "error: no alpine digest for major $major in manifest.json" >&2
    exit 1
  fi
  out_dir="${REPO_ROOT}/variants/${major}"
  mkdir -p "$out_dir"
  # Header marks the file as generated so reviewers know not to hand-edit it.
  {
    echo "# GENERATED by scripts/render-dockerfiles.sh — DO NOT EDIT."
    echo "# Edit Dockerfile.template + manifest.json, then re-run the script."
    # Substitute tokens, then drop the template's documentation header (every
    # line before the FROM instruction) so the generated file is clean.
    sed \
      -e "s|__PG_MAJOR__|${major}|g" \
      -e "s|__ALPINE_DIGEST__|${digest}|g" \
      -e "s|__PGVECTOR_VERSION__|${PGVECTOR}|g" \
      "$TEMPLATE" \
      | awk '/^FROM /{f=1} f'
  } > "${out_dir}/Dockerfile"
  echo "rendered variants/${major}/Dockerfile  (pg ${major}, pgvector ${PGVECTOR}, ${digest})"
done
